### ISSUE TITLE
Social Rumbles Open Source Code

### ISSUE THREAD

**Issue by sonicx180** [Dheirya/dheiryaweb#1]
Hey Dheirya! Do you have the Open Source Code of Social Rumbles ? Thanks!

**Comment by Dheirya** [comment]
Hi! Sorry, Social Rumbles is not Open Source, because of Security Reasons and because I don't want people to blatantly copy the whole site... if there's any specific part of the site you want the code of I'd be happy to give that, but not the full source code. Sorry!

**Comment by sonicx180** [comment]
I completely understand ! btw, did you use plain HTML,CSS, and JS because
when you view the source, it looks kinda messy like a next.js app ( I can
tell it is not though). Thanks!

**Comment by Dheirya** [comment]
No, I also use jQuery and a python web framework, plus a lot of other JS and python libraries... my source code is generally messy being honest because I've coded this project for about a little over a year so it's gotten really complex and intricate 😅

**Comment by sonicx180** [comment]
oh, I see. It happens a lot. just look at google's source code (the js part).

**Comment by sonicx180** [comment]
Also, you used django (as the python web framework) right?

**Comment by Dheirya** [comment]
Yeah I did, also the reason google's source code looks so jumbled is actually on purpose; it's called minifying and it compresses the file size making it faster to download and subsequently run across the web. Just a fun fact :)

**Comment by sonicx180** [comment]
That's cool! thanks!
